name: Build-AssImp
on:
  workflow_dispatch:

jobs:
  Build-AssImp-Windows:
    runs-on: windows-latest
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake git

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          cygwin: 1

      - name: Clone AssImp v5.1.6
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
        run: git clone -b v5.1.6 https://github.com/assimp/assimp
  
      - name: CMake AssImp
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
        run: cd assimp && cmake CMakeLists.txt -D ASSIMP_BUILD_ZLIB=OFF -D ASSIMP_BUILD_ASSIMP_TOOLS=OFF -G "MinGW Makefiles"
  
      - name: Build AssImp
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
        run: cd assimp && cmake --build . --parallel 2
  
      - name: Copy artifcats
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
        run: mkdir artifcats && cp -r ./assimp/bin artifcats/bin && cp -r ./assimp/lib artifcats/lib

      - name: Upload libraries to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assimp-libs-windows-x64
          path: artifcats

  Build-AssImp-MacOS:
    runs-on: macos-10.15
    steps:
      - name: Clone AssImp v5.1.6
        run: git clone -b v5.1.6 https://github.com/assimp/assimp
      - name: CMake AssImp
        working-directory: ./assimp
        run: cmake CMakeLists.txt -D ASSIMP_BUILD_ZLIB=OFF -D ASSIMP_BUILD_ASSIMP_TOOLS=OFF
      - name: Build AssImp
        working-directory: ./assimp
        run: cmake --build . --parallel 2
      - name: Upload libraries to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assimp-libs-macos-x64
          path: ./assimp/bin
