name: hello-world-example
on:
  workflow_dispatch:

jobs:
  Build-AssImp-MacOS:
    runs-on: macos-latest
    steps:
      - name: Clone AssImp v5.1.6
        run: git clone -b v5.1.6 https://github.com/assimp/assimp
      - name: CMake AssImp
        working-directory: ./assimp
        run: cmake CMakeLists.txt -D ASSIMP_BUILD_ZLIB=OFF -D ASSIMP_BUILD_ASSIMP_TOOLS=OFF
      - name: Build AssImp
        working-directory: ./assimp
        run: cmake --build . --parallel 6
      - name: View built
        working-directory: ./assimp
        run: ls -al ./bin
