name: hello-world-example
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: macos-latest
    steps:
      - name: Test cmake
        run: cmake --version
      - name: Test clang
        run: clang -v
      - name: Clone AssImp v5.1.6
        run: git clone -b v5.1.6 https://github.com/assimp/assimp

